# Generated by Django 4.2.5 on 2023-11-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='raport_url',
            field=models.CharField(default='raports/raport_11.pdf', max_length=256),
            preserve_default=False,
        ),
    ]
